# API Documentation configuration
knife4j:
  enable: true
  production: false
  basic:
    enable: false

# SpringDoc configuration
springdoc:
  api-docs:
    enabled: true
    resolve-schema-properties: true
  swagger-ui:
    enabled: true
  model-converters:
    pageable-converter:
      enabled: true

# Disable chunked transfer encoding, use fixed Content-Length
server:
  compression:
    enabled: false
  http2:
    enabled: false
  servlet:
    context-path: /xiaozhi-esp32-api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
  tomcat:
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB
    use-fixed-length-response: true
    uri-encoding: UTF-8
    relaxed-query-chars: ['[',']','{','}']
    relaxed-path-chars: ['[',']','{','}']
  port: 8002

spring:
  http:
    encoding:
      force: true
      force-response: true
      charset: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false
  jackson:
    serialization:
      indent-output: false
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    time-zone: "Asia/Shanghai"
      
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xiaozhi_esp32_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: D7Xj810i1C
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
jasypt:
  encryptor:
    password: P9Hx718z8L